// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using My_Core_4Table.Data;

namespace My_Core_4Table.Migrations
{
    [DbContext(typeof(MagazaDBContext))]
    [Migration("20220531001555_CreateDb")]
    partial class CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("My_Core_4Table.Models.Personeller", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADSOYAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CINSIYET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TOPLAMCALISMA")
                        .HasColumnType("int");

                    b.Property<int>("YAS")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Personellers");
                });

            modelBuilder.Entity("My_Core_4Table.Models.Subeler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KONUM")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TOPLAMCALISAN")
                        .HasColumnType("int");

                    b.Property<int>("YILLIKCIRO")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Subelers");
                });

            modelBuilder.Entity("My_Core_4Table.Models.Toptancilar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADISOYADI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KONUMU")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TELEFONNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TOPLAMCALISMA")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Toptancilars");
                });

            modelBuilder.Entity("My_Core_4Table.Models.Urunler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EKOZELLIKLER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FIYAT")
                        .HasColumnType("int");

                    b.Property<string>("MARKA")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Urunlers");
                });
#pragma warning restore 612, 618
        }
    }
}
